### ISSUE TITLE
Version of “lv_drivers” doesnt match that of lvgl

### ISSUE THREAD

**Issue by puppies** [littlevgl/lv_linux_frame_buffer#1]
I got this error when compiling with touch lib.

> lv_linux_frame_buffer/lv_drivers/indev/libinput.h:26:38: fatal error: lvgl/lv_hal/lv_hal_indev.h: No such file or directory

**Comment by embeddedt** [comment]
It just needs to be updated to point to the latest commit on `master`.

```shell
cd lv_drivers
git checkout master
git pull
cd ..
# Compile again
```

**Comment by embeddedt** [comment]
I will update it on the upstream end when I get a chance.

**Comment by embeddedt** [comment]
And it has not been updated yet.. because I didn't put this on my list. I will get around to it (soon).

**Comment by kisvegabor** [comment]
I've just updated all 3 submodules.
