### ISSUE TITLE
Zybo-Z7-10 Petalinux /dev/fb0 frame buffer fbdev

### ISSUE THREAD

**Issue by martin-scott-bluefruit** [littlevgl/lv_linux_frame_buffer#2]
I have downloaded and cross compiled the demo on Ubuntu VM. Following transfer to the Zybo it runs under Petalinux but the image is distorted and lined.

If I run fbset I get

![image](https://user-images.githubusercontent.com/45394098/64021033-f4f0d680-cb2a-11e9-845e-f5a129c25d3d.png)

Can this be fixed with some parameter changes in the demo?

**Comment by embeddedt** [comment]
What is the problem?

**Comment by martin-scott-bluefruit** [comment]
Hi, the image is distorted - it is double width, looks monochrome, and has vertical striations. The text is readable.

**Comment by embeddedt** [comment]
It's likely that `lv_drivers/display/fbdev.c` needs some modifications to accomodate your framebuffer's color format.

**Comment by martin-scott-bluefruit** [comment]
ok, i'll do some more research, thanks

**Comment by martin-scott-bluefruit** [comment]
Problem seems to be that memcpy (in fbdev_flush) cannot be used to copy to this 24bpp framebuffer because the color_p format is 32 bits. Therefore memcpy should be substituted with a version that skips every 4th byte, or support for a different color_p format is required. I tried changing petalinux /dev/fb0 to 32bpp but it does not seem to stick.

**Comment by embeddedt** [comment]
> memcpy should be substituted with a version that skips every 4th byte

This is probably the simplest solution.
